services:
  postgres:
    image: postgres:15 # Use the desired PostgreSQL version
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: scheduling
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7 # Use the desired Redis version
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  flyway:
    image: flyway/flyway:9.22.0
    container_name: flyway
    depends_on:
      - postgres
    entrypoint: [
      "flyway",
      "-url=jdbc:postgresql://postgres:5432/job_orchestrator",
      "-user=postgres",
      "-password=root",
      "migrate"
    ]
    volumes:
      - ./migrations:/flyway/sql

volumes:
  postgres-data: # Named volume for PostgreSQL data persistence

networks:
  app-network:
    driver: bridge
