name: Java CI

on:
  push:
    branches:
      - 'main'
      - 'feature/*'
      - 'fix/*'
  pull_request:
    branches:
      - 'main'
      - 'feature/*'
      - 'fix/*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Build and Run Checks
        run: ./gradlew build

      - name: Run Tests
        run: ./gradlew test

      - name: Run PMD
        run: ./gradlew pmdMain

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain

      - name: Upload Checkstyle Report (if failed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: build/reports/checkstyle/main.xml

      - name: Upload PMD Report (if failed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: pmd-report
          path: build/reports/pmd/main.xml
